# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
      # Linting
      - /gitlab-templates/reuse-lint.yml
      - /gitlab-templates/xml-lint.yml
      - /gitlab-templates/pre-commit.yml
      # Quality checks
      - /gitlab-templates/cppcheck.yml
      # CI Qt6
      - /gitlab-templates/linux-qt6-lts.yml
  
# Customize the job from /gitlab-templates/xml-lint.yml
# to use our own validate-xml-files.py which has some advanced
# features to validate Kdenlive specific xml files
xml:
  before_script: ''
  script:
    - git config --global --add safe.directory $CI_PROJECT_DIR
    - python3 -u ./validate-xml-files.py --verbose --check-all
