# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/breeze-icons' : 'Frameworks/6.24'
    'frameworks/karchive' : 'Frameworks/6.24'
    'frameworks/kbookmarks' : 'Frameworks/6.24'
    'frameworks/kconfig' : 'Frameworks/6.24'
    'frameworks/kconfigwidgets' : 'Frameworks/6.24'
    'frameworks/kcompletion' : 'Frameworks/6.24'
    'frameworks/kcoreaddons' : 'Frameworks/6.24'
    'frameworks/kcrash' : 'Frameworks/6.24'
    'frameworks/kdbusaddons' : 'Frameworks/6.24'
    'frameworks/kguiaddons' : 'Frameworks/6.24'
    'frameworks/ki18n' : 'Frameworks/6.24'
    'frameworks/kiconthemes' : 'Frameworks/6.24'
    'frameworks/kio' : 'Frameworks/6.24'
    'frameworks/kitemviews' : 'Frameworks/6.24'
    'frameworks/kjobwidgets' : 'Frameworks/6.24'
    'frameworks/knewstuff' : 'Frameworks/6.24'
    'frameworks/knotifications' : 'Frameworks/6.24'
    'frameworks/knotifyconfig' : 'Frameworks/6.24'
    'frameworks/kplotting' : 'Frameworks/6.24'
    'frameworks/kservice' : 'Frameworks/6.24'
    'frameworks/ktextwidgets' : 'Frameworks/6.24'
    'frameworks/kwidgetsaddons' : 'Frameworks/6.24'
    'frameworks/kxmlgui' : 'Frameworks/6.24'
    'frameworks/kfilemetadata' : 'Frameworks/6.24'
    'frameworks/purpose' : 'Frameworks/6.24'

#- 'on': ['Linux', 'FreeBSD']
  #'require':
    #'plasma/drkonqi' : '@stable'
RuntimeDependencies:
- 'on': ['Linux']
  'require':
    'sdk/selenium-webdriver-at-spi': '@latest-kf6'

Options:
  require-passing-tests-on: [ 'Linux/Qt6', 'FreeBSD/Qt6']
  cppcheck-arguments: ['--suppress=*:tests/fakeit.hpp', '--suppress=*:tests/catch.hpp', '--suppress=*:fuzzer/fakeit_standalone.hpp']
  require-cppcheck-clean: True
  per-test-timeout: 120

