# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/breeze-icons' : '@latest-kf6'
    'frameworks/karchive' : '@latest-kf6'
    'frameworks/kbookmarks' : '@latest-kf6'
    'frameworks/kconfig' : '@latest-kf6'
    'frameworks/kconfigwidgets' : '@latest-kf6'
    'frameworks/kcompletion' : '@latest-kf6'
    'frameworks/kcoreaddons' : '@latest-kf6'
    'frameworks/kcrash' : '@latest-kf6'
    'frameworks/kdbusaddons' : '@latest-kf6'
    'frameworks/kguiaddons' : '@latest-kf6'
    'frameworks/ki18n' : '@latest-kf6'
    'frameworks/kiconthemes' : '@latest-kf6'
    'frameworks/kio' : '@latest-kf6'
    'frameworks/kitemviews' : '@latest-kf6'
    'frameworks/kjobwidgets' : '@latest-kf6'
    'frameworks/knewstuff' : '@latest-kf6'
    'frameworks/knotifications' : '@latest-kf6'
    'frameworks/knotifyconfig' : '@latest-kf6'
    'frameworks/kplotting' : '@latest-kf6'
    'frameworks/kservice' : '@latest-kf6'
    'frameworks/ktextwidgets' : '@latest-kf6'
    'frameworks/kwidgetsaddons' : '@latest-kf6'
    'frameworks/kxmlgui' : '@latest-kf6'
    'frameworks/kfilemetadata' : '@latest-kf6'
    'frameworks/purpose' : '@latest-kf6'

#- 'on': ['Linux', 'FreeBSD']
  #'require':
    #'plasma/drkonqi' : '@stable'
RuntimeDependencies:
- 'on': ['Linux']
  'require':
    'sdk/selenium-webdriver-at-spi': '@latest-kf6'

RuntimeDependencies:
- 'on': ['Linux']
  'require':
    'sdk/selenium-webdriver-at-spi': '@latest-kf6'

Options:
  require-passing-tests-on: [ 'Linux/Qt6', 'FreeBSD/Qt6']
  cppcheck-arguments: ['--suppress=*:tests/fakeit.hpp', '--suppress=*:tests/catch.hpp', '--suppress=*:fuzzer/fakeit_standalone.hpp']
  require-cppcheck-clean: False
  per-test-timeout: 120

