# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

[General]
DisableDefaultImports=false
MaxWarnings=-1

[Warnings]
AccessSingletonViaObject=error
AliasCycle=error
AssignmentInCondition=error
AttachedPropertyReuse=disable
BadSignalHandlerParameters=error
Comma=error
CompilerWarnings=disable
ComponentChildrenCount=error
ConfusingExpressionStatement=error
ConfusingMinuses=error
ConfusingPluses=error
ContextProperties=error
Deprecated=error
DuplicateEnumEntries=error
DuplicateImport=error
DuplicateInlineComponent=error
DuplicatePropertyBinding=error
DuplicatedName=error
EnumEntryMatchesEnum=error
EnumsAreNotTypes=error
EqualityTypeCoercion=error
Eval=error
FunctionUsedBeforeDeclaration=disable
ImportFailure=error
ImportFileSelector=disable
IncompatibleType=warning
InheritanceCycle=error
InvalidLintDirective=error
LintPluginWarnings=disable
LiteralConstructor=error
MissingEnumEntry=error
MissingProperty=warning
MissingType=error
MultilineStrings=info
NonListProperty=error
NonRootEnum=error
PreferNonVarProperties=error
PrefixedImportType=error
QtDesignStudio.FunctionsNotSupportedInQmlUi=error
QtDesignStudio.ImperativeCodeNotEditableInVisualDesigner=error
QtDesignStudio.InvalidIdeInVisualDesigner=error
QtDesignStudio.ReferenceToParentItemNotSupportedByVisualDesigner=error
QtDesignStudio.UnsupportedRootTypeInQmlUi=error
QtDesignStudio.UnsupportedTypeInQmlUi=error
Quick.Anchors=warning
Quick.AttachedPropertyReuse=disable
Quick.AttachedPropertyType=error
Quick.Color=error
Quick.ControlsAttachedPropertyReuse=disable
Quick.ControlsNativeCustomize=error
Quick.LayoutsPositioning=warning
Quick.PropertyChangesParsed=warning
Quick.StateNoChildItem=error
Quick.UnexpectedVarType=error
ReadOnlyProperty=error
RedundantOptionalChaining=error
RequiredProperty=error
RestrictedType=error
StalePropertyRead=error
TopLevelComponent=error
TranslationFunctionMismatch=error
UncreatableType=error
UnintentionalEmptyBlock=error
UnqualifiedAccess=warning
UnreachableCode=error
UnresolvedAlias=error
UnresolvedType=error
UnterminatedCase=error
UnusedImports=info
UseProperFunction=error
VarUsedBeforeDeclaration=error
Void=disable
WithStatement=error
