# This spec file was generated by Gideon
# Please report any problem to KDevelop Team <kdevelop-devel@kdevelop.org>
# Thanks to Matthias Saou for his explanations on http://freshrpms.net/docs/fight.html

Name: kdenlive
Version: 0.2.2
Release: 26/4/2003
Vendor: 
Copyright: GPL
Summary: A non-linear video editor
Group: 
Packager: Jason Wood <jasonwood@blueyonder.co.uk>
BuildRoot: %{_tmppath}/%{name}-root
Source: kdenlive-0.2.2.tar.gz

%description
Kdenlive is a non-linear vdeo editor for KDE. It relies on a seperate renderer, piave, to handle it's rendering. Kdenlive supports multitrack editing.

%prep
%setup
CFLAGS="$RPM_OPT_FLAGS" CXXFLAGS="$RPM_OPT_FLAGS" ./configure \
--target=i386

%build
%configure
make

%install
rm -rf %{buildroot}
%makeinstall

%clean
rm -rf %{buildroot}

%post -p /sbin/ldconfig
%postun -p /sbin/ldconfig
%files
%defattr(-, root, root)
%doc AUTHORS COPYING ChangeLog NEWS README TODO
%{_bindir}/*
%{_libdir}/*.so.*
%{_datadir}/%{name}
%{_mandir}/man8/*
%changelog

