#!/bin/sh
# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

# Drop stderr
exec 2> /dev/null

echo "/* SPDX-FileCopyrightText: None" > rc2.cpp
echo "   SPDX-License-Identifier: CC0-1.0 */" >> rc2.cpp
echo "" >> rc2.cpp
echo "// This file is automatically generated by mlt-translate.sh" >> rc2.cpp
echo "// Do not modify" >> rc2.cpp
echo "" >> rc2.cpp

list="lumakey frei0r.premultiply frei0r.spillsupress frei0r.bw0r avfilter.grayworld frei0r.invert0r avfilter.swapuv avfilter.alphaextract avfilter.backgroundkey avfilter.colordetect frei0r.ndvi avfilter.gradfun"
for i in $list; do 
    echo "// ============== $i =============="  >> rc2.cpp
    index=1
    var=$(melt -query filter=$i)
    while IFS= read -r line; do
        if [[ $line == "title: "* ]];
        then
            echo "// Name" >> rc2.cpp
            echo "i18n(\"${line:7}\");" >> rc2.cpp
        fi
        if [[ $line == "    title: "* ]];
        then
            echo "// Parameter $index" >> rc2.cpp
            echo "i18n(\"${line:11}\");" >> rc2.cpp
            ((index++))
        fi
    done <<< "$var"
done
