/* SPDX-FileCopyrightText: None
   SPDX-License-Identifier: CC0-1.0 */

// This file is automatically generated by mlt-translate.sh
// Do not modify

// ============== lumakey ==============
// Name
i18n("Lumakey");
// Parameter 1
i18n("Threshold");
// Parameter 2
i18n("Slope");
// Parameter 3
i18n("Pre-Threshold Luma Level");
// Parameter 4
i18n("Post-Threshold Luma Level");
// ============== frei0r.premultiply ==============
// Name
i18n("Premultiply or Unpremultiply");
// Parameter 1
i18n("unpremultiply");
// ============== frei0r.spillsupress ==============
// Name
i18n("spillsupress");
// Parameter 1
i18n("supresstype");
// ============== frei0r.bw0r ==============
// Name
i18n("bw0r");
// ============== avfilter.grayworld ==============
// Name
i18n("grayworld");
// ============== frei0r.invert0r ==============
// Name
i18n("Invert0r");
// ============== avfilter.swapuv ==============
// Name
i18n("swapuv");
// ============== avfilter.alphaextract ==============
// Name
i18n("alphaextract");
// ============== avfilter.backgroundkey ==============
// Name
i18n("backgroundkey");
// ============== avfilter.colordetect ==============
// Name
i18n("colordetect");
// ============== frei0r.ndvi ==============
// Name
i18n("NDVI filter");
// Parameter 1
i18n("Color Map");
// Parameter 2
i18n("Levels");
// Parameter 3
i18n("VIS Scale");
// Parameter 4
i18n("VIS Offset");
// Parameter 5
i18n("NIR Scale");
// Parameter 6
i18n("NIR Offset");
// Parameter 7
i18n("Visible Channel");
// Parameter 8
i18n("NIR Channel");
// Parameter 9
i18n("Index Calculation");
// Parameter 10
i18n("Legend");
// ============== avfilter.gradfun ==============
// Name
i18n("gradfun");
