#!/bin/bash
cp ox16-action-kdenlive-zindex-up.png hi16-action-kdenlive-zindex-up.png
cp oxsc-action-kdenlive-zindex-up.svgz hisc-action-kdenlive-zindex-up.svgz
cp ox16-action-kdenlive-zindex-down.png hi16-action-kdenlive-zindex-down.png
cp oxsc-action-kdenlive-zindex-down.svgz hisc-action-kdenlive-zindex-down.svgz
cp ox16-action-kdenlive-zindex-top.png hi16-action-kdenlive-zindex-top.png
cp oxsc-action-kdenlive-zindex-top.svgz hisc-action-kdenlive-zindex-top.svgz
cp ox16-action-kdenlive-zindex-bottom.png hi16-action-kdenlive-zindex-bottom.png
cp oxsc-action-kdenlive-zindex-bottom.svgz hisc-action-kdenlive-zindex-bottom.svgz
cp ox16-action-kdenlive-object-width.png hi16-action-kdenlive-object-width.png
cp oxsc-action-kdenlive-object-width.svgz hisc-action-kdenlive-object-width.svgz
cp ox16-action-kdenlive-object-height.png hi16-action-kdenlive-object-height.png
cp oxsc-action-kdenlive-object-height.svgz hisc-action-kdenlive-object-height.svgz
cp oxsc-action-kdenlive-insert-rect.svgz hisc-action-kdenlive-insert-rect.svgz
cp oxsc-action-kdenlive-select-rects.svgz hisc-action-kdenlive-select-rects.svgz
cp ox16-action-kdenlive-select-rects.png hi16-action-kdenlive-select-rects.png
cp oxsc-action-kdenlive-select-texts.svgz hisc-action-kdenlive-select-texts.svgz
cp oxsc-action-kdenlive-unselect-all.svgz hisc-action-kdenlive-unselect-all.svgz
cp oxsc-action-kdenlive-select-all.svgz hisc-action-kdenlive-select-all.svgz
cp ox16-action-kdenlive-unselect-all.png hi16-action-kdenlive-unselect-all.png
cp ox16-action-kdenlive-select-texts.png hi16-action-kdenlive-select-texts.png
cp ox16-action-kdenlive-select-images.png hi16-action-kdenlive-select-images.png
cp ox16-action-kdenlive-select-all.png hi16-action-kdenlive-select-all.png