/***************************************************************************
                          kdenliveview.h  -  description
                             -------------------
    begin                : Fri Feb 15 01:46:16 GMT 2002
    copyright            : (C) 2002 by Jason Wood
    email                : jasonwood@blueyonder.co.uk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

#ifndef KDENLIVEVIEW_H
#define KDENLIVEVIEW_H

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif 

// include files for Qt
#include <qsplitter.h>
#include <qgrid.h>

//include files for KDE
#include <qlabel.h>

// include files for project
#include <kmmtimeline.h>
#include <kruler.h>
#include <kmmmonitor.h>
#include <projectlist.h>


class KdenliveDoc;

/** The KdenliveView class provides the view widget for the KdenliveApp instance.	
 * The View instance inherits QWidget as a base class and represents the view object of a KTMainWindow. As KdenliveView is part of the
 * docuement-view model, it needs a reference to the document object connected with it by the KdenliveApp class to manipulate and display
 * the document structure provided by the KdenliveDoc class.
 * 	
 * @author Source Framework Automatically Generated by KDevelop, (c) The KDevelop Team.
 * @version KDevelop version 0.4 code generation
 */
class KdenliveView : public QSplitter
{
  Q_OBJECT
  public:
    /** Constructor for the main view */
    KdenliveView(QWidget *parent = 0, const char *name=0);
    /** Destructor for the main view */
    ~KdenliveView();

    /** returns a pointer to the document connected to the view instance. Mind that this method requires a KdenliveApp instance as a parent
     * widget to get to the window document pointer by calling the KdenliveApp::getDocument() method.
     *
     * @see KdenliveApp#getDocument
     */
    KdenliveDoc *getDocument() const;

    /** contains the implementation for printing functionality */
    void print(QPrinter *pPrinter);
	
  private:
  	QSplitter m_topSplitter;  	
  	ProjectList m_projectList;
  	KMMMonitor m_monitor;
		KMMTimeLine m_timeline;
};

#endif // KDENLIVEVIEW_H
