#
# Find the FFMPEG includes and library
#

FIND_PROGRAM(FFMPEG_CONFIG_EXECUTABLE pkg-config)
EXEC_PROGRAM(${FFMPEG_CONFIG_EXECUTABLE} ARGS --variable=includedir libavformat OUTPUT_VARIABLE FFMPEG_HEADER_PATH )
MESSAGE(STATUS "Found FFmpeg header pkg-config: ${FFMPEG_CONFIG_EXECUTABLE} , ${FFMPEG_HEADER_PATH}")
EXEC_PROGRAM(${FFMPEG_CONFIG_EXECUTABLE} ARGS --variable=libdir libavformat OUTPUT_VARIABLE FFMPEG_LIBS_PATH )
MESSAGE(STATUS "Found FFmpeg lib pkg-config: ${FFMPEG_CONFIG_EXECUTABLE} , ${FFMPEG_LIBS_PATH}")


FIND_PATH(LIBFFMPEG_INCLUDE_DIR 
  NAMES avformat.h
  PATHS ${FFMPEG_HEADER_PATH}/ffmpeg ${FFMPEG_HEADER_PATH}/libavformat ${FFMPEG_HEADER_PATH}/ffmpeg/libavformat
  NO_DEFAULT_PATH
)

MESSAGE(STATUS "Found FFmpeg INCLUDES: ${LIBFFMPEG_INCLUDE_DIR}")

FIND_LIBRARY(LIBFFMPEG_LIBRARY
  NAMES avformat
  PATHS ${FFMPEG_LIBS_PATH}
  NO_DEFAULT_PATH
)

IF (LIBFFMPEG_LIBRARY AND LIBFFMPEG_INCLUDE_DIR)
  SET( LIBFFMPEG_FOUND 1 )
  SET( LIBFFMPEG_LIBRARIES ${LIBFFMPEG_LIBRARY} )
ELSE (LIBFFMPEG_LIBRARY AND LIBFFMPEG_INCLUDE_DIR)
  SET( LIBFFMPEG_FOUND 0 )
ENDIF (LIBFFMPEG_LIBRARY AND LIBFFMPEG_INCLUDE_DIR)

IF (LIBFFMPEG_FOUND)
  IF (NOT LIBFFMPEG_FIND_QUIETLY)
    MESSAGE(STATUS "Found FFmpeg library: ${LIBFFMPEG_LIBRARY}")
  ENDIF (NOT LIBFFMPEG_FIND_QUIETLY)
ELSE (LIBFFMPEG_FOUND)
  IF (LIBFFMPEG_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find FFMPEG library")
  ENDIF (LIBFFMPEG_FIND_REQUIRED)
ENDIF (LIBFFMPEG_FOUND)

